---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: zpool-solaris-11
    driver:
      box: chef/solaris-11.3
    run_list:
      - recipe[kitchen_aide::solaris_busser]
  - name: ubuntu-16.04
  - name: freebsd-11.1
suites:
  - name: default
    run_list:
      - recipe[zpool_tester::default]
